version: '3'
services:
  web:
    build: .
    ports:
    - "8070:8070"
    - "1883:1883"
    - "8090:8090"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - mongo
  mongo:
    image: mongo
    volumes:
    - /data/db
volumes:
  logvolume01: {}